const OK = 200;
const CREATED = 201;
const UPDATED = 202;
const BADREQUEST = 400;
const NOTFOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = { OK, CREATED, UPDATED, BADREQUEST, NOTFOUND, INTERNAL_SERVER_ERROR };