const OK_MESSAGE = "SUCCESS";
const CREATED_MESSAGE = "CREATED";
const UPDATED_MESSAGE = "UPDATED";
const BADREQUEST_MESSAGE = "BADREQUEST";
const NOTFOUND_MESSAGE = "NOT FOUND";
const INTERNAL_SERVER_ERROR_MESSAGE = "INTERNAL SERVER ERROR";

module.exports = { OK_MESSAGE, CREATED_MESSAGE, UPDATED_MESSAGE, NOTFOUND_MESSAGE, BADREQUEST_MESSAGE, INTERNAL_SERVER_ERROR_MESSAGE };